manifest = "059dd4dd7a433ac637a02287a94ef8aa8a5c69efc0eb1b9993db23f67e0370cb"

[[dependency]]
package = "github.com/buckaroo-pm/host-pthread"
target = "//:pthread"

[lock."github.com/buckaroo-pm/host-pthread"]
versions = [ "branch=master" ]
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"
